name: Update VPN Configs

on:
  schedule:
    - cron: '0 */12 * * *'  # هر 12 ساعت
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create virtual environment
        run: python -m venv venv --copies

      - name: Upgrade pip
        run: ./venv/bin/python -m pip install --upgrade pip

      - name: Install dependencies
        run: ./venv/bin/python -m pip install -r source/requirements.txt

      - name: Verify installation
        run: ./venv/bin/python -m pip list

      - name: Run main.py
        run: |
          source ./venv/bin/activate
          python source/main.py
