name: Update VPN Configs

on:
  schedule:
    - cron: '0 */12 * * *'   # هر ۱۲ ساعت یک بار
  workflow_dispatch:  # برای اجرا به صورت دستی

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
      # ۱. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # ۲. Setup Python 3.x
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # ۳. Install dependencies from requirements.txt without cache
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r source/requirements.txt

      # ۴. Debug: List installed packages
      - name: Debug: List installed packages
        run: |
          pip list

      # ۵. Run main.py to update configs
      - name: Run main.py
        run: |
          python source/main.py
        continue-on-error: false

      # ۶. Commit and push changes safely
      - name: Commit and push changes
        env:
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin main
          git reset --hard origin/main
          git add .
          git diff --cached --quiet || (
            git commit -m "Auto update VPN configs $(date '+%Y-%m-%d %H:%M:%S')"
            git push https://x-access-token:${GIT_TOKEN}@github.com/ShatakVPN/ConfigForge-V2Ray.git main
          )
