name: Update VPN Configs

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت یک بار اجرا میشه، میتونی تغییرش بدی
  workflow_dispatch:  # امکان اجرا دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main.py
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        REPO_NAME: ShatakVPN/ConfigForge
      run: python source/main.py
