name: Update VPN Configs

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        if [ -f source/requirements.txt ]; then pip install -r source/requirements.txt; fi

    - name: Run main.py
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        REPO_NAME: ShatakVPN/ConfigForge
      run: python source/main.py

    - name: Push changes
      env:
        # این متغیر برای git push استفاده می‌شود
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git add .
        git commit -m "Auto update VPN configs $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/ShatakVPN/ConfigForge.git main
