name: Update V2Ray Configs

on:
  workflow_dispatch:    # اجرای دستی از تب Actions
  schedule:
    - cron: '0 */6 * * *'  # اجرای خودکار هر ۶ ساعت یک‌بار

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # مرحله 1: کلون کردن ریپو
      - name: Checkout repository
        uses: actions/checkout@v4

      # مرحله 2: نصب پیش‌نیازها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests urllib3

      # مرحله 3: اجرای اسکریپت اصلی
      - name: Run main script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # توکن پیش‌فرض گیتهاب
          REPO_NAME: ShatakVPN/ConfigForge            # اسم ریپو رو اینجا بگذار
        run: |
          python source/main.py
