name: Update VPN Configs

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('source/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f source/requirements.txt ]; then pip install -r source/requirements.txt; fi

      - name: Run main.py to update configs
        run: |
          source venv/bin/activate
          python source/main.py
        continue-on-error: false

      - name: Commit and push changes if any
        env:
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions" && \
          git config user.email "actions@github.com" && \
          git add . && \
          git diff --cached --quiet || (git commit -m "Auto update VPN configs $(date '+%Y-%m-%d %H:%M:%S')" && git push https://x-access-token:${GIT_TOKEN}@github.com/ShatakVPN/ConfigForge-V2Ray.git main)
